<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>TiaProbe</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Siemens.Engineering">
      <HintPath>D:\TIA\Portal V18\PublicAPI\V18\Siemens.Engineering.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
